---
title: "Attempt1"
author: "AJ"
date: "3/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

rm(list=ls(all=T))

library(tidyverse)
library(ggplot2)
library(gtools)
library(OrgMassSpecR)
library(pracma)
library(RColorBrewer)

```


```{r}

#Name of file containing peptide data with extracted complement ions
#Data must have been collected with narrow quad width (e.g. 0.4 m/z) to prevent contamination
#from neighboring peaks in the isotopic envelope

input_text <- "ORC_02749_PD_PSMs_renamed_intermediate"
input <- read.csv(paste(input_text, ".csv", sep="")) 

input <- input %>% mutate(mz = (Theo..MH...Da. - 1.007276466812 + Charge * 1.007276466812) / Charge,
                          iso_mz_actual = Isolation.Mz)

```

```{r}

IsotopicDistribution_Peptide <- function(sequence, no_sims = 500, incorp = 0.00368, IAA = TRUE, charge = 2, 
                                  custom = list(code = NULL, elements = NULL)) {
    if(length(custom$elements != 0)) {
        custom_elements <- c(C = 0, H = 0, N = 0, O = 0, S = 0, P = 0)
        custom_elements[names(custom$elements)] <- custom$elements
    }
    if(charge < 1 | charge > 3) stop("charge must be 1, 2, or 3")
    seq_vector <- strsplit(sequence, split = "")[[1]]
    x <- c(C = 0, H = 0, N = 0, O = 0, S = 0, P = 0)
    for(i in 1:(length(seq_vector))) {
        if(seq_vector[i] == "A") x <- x + c(C = 3, H = 5, N = 1, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "R") x <- x + c(C = 6, H =12, N = 4, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "N") x <- x + c(C = 4, H = 6, N = 2, O = 2, S = 0, P = 0)
        if(seq_vector[i] == "D") x <- x + c(C = 4, H = 5, N = 1, O = 3, S = 0, P = 0)
        if(seq_vector[i] == "E") x <- x + c(C = 5, H = 7, N = 1, O = 3, S = 0, P = 0)
        if(seq_vector[i] == "Q") x <- x + c(C = 5, H = 8, N = 2, O = 2, S = 0, P = 0)
        if(seq_vector[i] == "G") x <- x + c(C = 2, H = 3, N = 1, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "H") x <- x + c(C = 6, H = 7, N = 3, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "I") x <- x + c(C = 6, H =11, N = 1, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "L") x <- x + c(C = 6, H =11, N = 1, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "K") x <- x + c(C = 6, H =12, N = 2, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "M") x <- x + c(C = 5, H = 9, N = 1, O = 1, S = 1, P = 0)
        if(seq_vector[i] == "F") x <- x + c(C = 9, H = 9, N = 1, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "P") x <- x + c(C = 5, H = 7, N = 1, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "S") x <- x + c(C = 3, H = 5, N = 1, O = 2, S = 0, P = 0)
        if(seq_vector[i] == "T") x <- x + c(C = 4, H = 7, N = 1, O = 2, S = 0, P = 0)
        if(seq_vector[i] == "W") x <- x + c(C =11, H =10, N = 2, O = 1, S = 0, P = 0)
        if(seq_vector[i] == "Y") x <- x + c(C = 9, H = 9, N = 1, O = 2, S = 0, P = 0)
        if(seq_vector[i] == "V") x <- x + c(C = 5, H = 9, N = 1, O = 1, S = 0, P = 0)
    
        ## if IAA = TRUE, unlabeled N from IAA added handled separately
        if(seq_vector[i] == "C" & IAA == TRUE) x <- x + c(C = 5, H = 8, N = 1, O = 2, S = 1, P = 0)
        if(seq_vector[i] == "C" & IAA == FALSE) x <- x + c(C = 3, H = 5, N = 1, O = 1, S = 1, P = 0)
        
        if(length(custom$elements != 0))
            if(seq_vector[i] == custom$code) x <- x + custom_elements    
    }
    ## add N-terminal H and C-terminal OH
    elements <- x + c(C = 0, H = 2, N = 0, O = 1, S = 0, P = 0) 
    
    simulation <- function(elements) {
        
        mz <- vector(mode="numeric")
    
        ## mass of carbons
        mc <- sum(sample(c(12.0000000, 13.0033548378), 
                         size = elements["C"],  
                         replace = TRUE, 
                         prob = c(0.9893, 0.0107)))
  
        ## mass of hydrogens
        mh <- sum(sample(c(1.0078250321, 2.0141017780), 
                         size = elements["H"],
                         replace = TRUE, 
                         prob = c(0.999885, 0.000115)))
                  
        ## mass of nitrogens, natural 15N incorporation is 0.00368
        mn <- sum(sample(c(14.0030740052, 15.0001088984), 
                         size = elements["N"], 
                         replace = TRUE, 
                         prob = c(1 - incorp, incorp)))
        ## mass of unlabeled IAA nitrogen(s)
        if(IAA == TRUE) {
        mn_iaa <- sum(sample(c(14.0030740052, 15.0001088984), 
                             size = length(grep("C", seq_vector)),
                             replace = TRUE,
                             prob = c(0.99632, 0.00368)))
        } else mn_iaa <- 0
        
        ## mass of oxygens
        mo <- sum(sample(c(15.9949146221, 16.99913150, 17.9991604), 
                         size = elements["O"], 
                         replace = TRUE, 
                         prob = c(0.99757, 0.00038, 0.00205)))
        ## mass of sulfers
        ms <- sum(sample(c(31.97207069, 32.97145850, 
                           33.96786683, 35.96708088), 
                         size = elements["S"], 
                         replace = TRUE, 
                         prob = c(0.9493, 0.0076, 0.0429, 0.0002)))
    
        ## mass of charge
        mch <- sum(sample(c(1.0072764522, 2.0135531981), 
                          size = charge, 
                          replace = TRUE, 
                          prob = c(0.999885, 0.000115)))
    
        ## m/z of molecule
        mz <- sum(mc, mh, mn, mo, ms, mch, mn_iaa) / charge 
        
        return(mz)  
    }
    
    ## run simulation
    sim <- replicate(no_sims, expr = simulation(elements))  
    
    ## bin ions
    b <- seq(from = min(sim) - (1 / (2 * charge)),
             to = max(sim) + 1, 
             by = 1 / charge)
    bins <- cut(sim, breaks = b)
    intensity <- as.vector(table(bins))
    intensity <- intensity[intensity!=0]
    spec <- round(intensity / sum(intensity), digits = 4)
          
    return(spec)
}


```




```{r}

#Get the reported S:N value of complement ions.
#AYnmin1Pmin1.Sn is the lightest complement ion at a mass loss of 162.1328 (plus a proton so 163.1418)
comp_start <- which(names(input)=="aYnmin1Pmin1.Sn")
measured_comp_env <- input[comp_start:(comp_start+11)]

z <- input$Charge
tmt <- lengths(regmatches(input$Annotated.Sequence, gregexpr("K", toupper(input$Annotated.Sequence))))+1

#Calculating the isotopic envelope of each peptide. Previously used peptide envelopes in a csv
#because the function is quite slow.
saved_peptide_envelopes <- read.csv("saved_peptide_envelopes.csv") %>% distinct(peptide_sequence, .keep_all=T)

pep_dist <- left_join(input %>% mutate(peptide_sequence = toupper(input$Annotated.Sequence)) %>%
            dplyr::select(peptide_sequence), saved_peptide_envelopes, by="peptide_sequence")

add_to_peptide_env <- pep_dist %>% filter(is.na(X1)) %>% distinct(peptide_sequence, .keep_all=T)

to_calc <- nrow(add_to_peptide_env)

if(to_calc>0){
  pracma::tic()
  for(i in 1:to_calc){
    pep_dist_now <- IsotopicDistribution_Peptide(add_to_peptide_env$peptide_sequence[i])
    add_to_peptide_env[i,2:13] <- c(pep_dist_now,rep(0, 12))[1:12]
    
    if(i %% 1000 ==0){
      print(i)
    }
  }
  pracma::toc()
  
  saved_peptide_envelopes <- rbind(saved_peptide_envelopes, 
        add_to_peptide_env[!is.na(add_to_peptide_env$X1),])
  
  #Write new peptide envelopes
  write.csv(saved_peptide_envelopes, "saved_peptide_envelopes.csv", row.names=F)
  
  #Should have all peptides now
  pep_dist <- left_join(input %>% mutate(peptide_sequence = toupper(input$Annotated.Sequence)) %>%
              dplyr::select(peptide_sequence), saved_peptide_envelopes, by="peptide_sequence")
}

sum(is.na(pep_dist$X1)) #Should be 0 now

iso_peak <- round((input$iso_mz_actual - input$mz)*z,0)

#Re-make dataframe with only relevant parameters
combined_df <- data.frame(measured_comp_env, pep_dist, iso_peak, tmt, input)
names(combined_df)[1:12] <- paste("comp_signal_",1:12, sep="")
names(combined_df)[14:25] <- paste("peptide_env_",0:11, sep="")

combined_df <- combined_df %>% filter(iso_peak>=0 & iso_peak<=2)

#Calculate the total S:N in the complement envelope
sumsn <- vector(length=dim(combined_df)[1])

for(i in 1:dim(combined_df)[1]){
  sumsn[i] <- sum(combined_df[i,(1+min(combined_df$iso_peak[i],3)):(1+min(combined_df$iso_peak[i],3)+8)])
}

data <- cbind(combined_df, sumsn)

```


```{r}

#Build matrix once for reporter impurities.
repCO_impurity <- read.csv(file="TMTpro9plex_RCO_impurity_241003.csv", header=T)
repCO_impurity_matrix <- matrix(nrow=9,ncol=9)

for(p in 1:9){
  for(j in 1:9){
    if(p==j){
      repCO_impurity_matrix[p,j] <- repCO_impurity[10-j,3]
    } else if(p==(j-1)){
      repCO_impurity_matrix[p,j] <- repCO_impurity[10-j,4]
    } else if(p==(j+1)){
      repCO_impurity_matrix[p,j] <- repCO_impurity[10-j,2]
    } else if(p==(j-2)){
      repCO_impurity_matrix[p,j] <- repCO_impurity[10-j,5]
    } else if(p==(j+2)){
      repCO_impurity_matrix[p,j] <- repCO_impurity[10-j,1]
    } else{
      repCO_impurity_matrix[p,j] <- 0
    }
  }
}

comp_impurity <- read.csv(file="TMTpro9plex_comp_impurity_241003.csv", header=T, row.names=NULL)
comp_impurity <- comp_impurity[dim(comp_impurity)[1]:1,]

total_impurity <- read.csv(file="TMTpro9plex_total_impurity_241003.csv", header=T)
total_impurity <- total_impurity[dim(total_impurity)[1]:1,]


which_channels <- c(1,1,1,1,1,1,1,1,1)
M1trans <- 0.0

#Define function for isotopic impurity correction
remove_impurities <- function(row){
  if(data$sumsn[row]<10 | data$iso_peak[row]<0 | data$iso_peak[row]>3){
    return(rep(0,9))
  }
  
  #row <- 1
  
  no_tmt <- data$tmt[row]
  isolated_precursor <- data$iso_peak[row]
  
  pep_env_start <- which(names(data)=="peptide_env_0")
  pep_env <- as.vector(t(data[row,pep_env_start:(pep_env_start+11)]))
  
  trans_mat <- zeros(9)
  trans_mat1 <- zeros(9)
  
  #Add comp ion convolution
  for(i in 1:9){
    temp_conv <- pep_env
    temp_conv <- conv(temp_conv, as.matrix(comp_impurity)[i,])
    if(no_tmt>1){
      for(j in 1:(no_tmt-1)){
        temp_conv <- conv(temp_conv, as.matrix(total_impurity)[i,])
      }
    }
    
    trans_mat[,i] <- c(rep(0, max(0,i-2*no_tmt-isolated_precursor-1)),
                       temp_conv[max(1,2-i+2*no_tmt+isolated_precursor):(2*no_tmt + 10 -i+isolated_precursor)])
    
    #Peak one to the right
    trans_mat1[,i] <- c(0,(c(rep(0, max(0,i-2*no_tmt-isolated_precursor-2)),
                       temp_conv[max(1,3-i+2*no_tmt+isolated_precursor):(2*no_tmt + 11 -i+isolated_precursor)]) *
      repCO_impurity_matrix[,i])[1:8]) * M1trans
  }
  
  trans_mat <- trans_mat * repCO_impurity_matrix
  trans_mat <- trans_mat + trans_mat1
  trans_mat <- trans_mat[which_channels==1, which_channels==1]

  ratio_start <- which(names(data)=="comp_signal_1")
  all_ratios <-  as.vector(t(data[row,(ratio_start+isolated_precursor):
                                    (ratio_start+isolated_precursor+8)]))[which_channels==1]
  # Solve the system of equations
  solution <- solve(trans_mat,all_ratios)
  
  if((row %% 5000 ==0)){
    print(row)
  }
  
  solution[solution<0] <- 0
  solution[9:1]/sum(solution)
  
}

#Run the function over each peptide
corrected_ratios <- t(mapply(remove_impurities, 1:nrow(data))) 

colnames(corrected_ratios) <- paste("ratio", 1:9, sep="")

```

```{r}

write.csv(cbind(data, corrected_ratios), paste(input_text,"_tmtc_analytical.csv",sep=""), row.names=F)

```




